sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
before_install: gem install bundler -v 1.16.2
notifications:
  slack:
    secure: "zxLdcLe9Vb/HiuhMZssIP4iuemZ+sISFo2EM0NuAryku52iAXOspozyNt6JMny/erQ8huOsBO5hjXc4hgaozADeXmmc4boUb/ejeJ28Z3q4k9hSsOksQ1cLNXRaljuDoog/Lp5ul5Z1KN0H26Kt0zZHp+gIYZbsh3u39zmu/cZnbxZKpSNqvmTTR0ZB6scRh1f0XQDLAe/p0tObBb+u8Wd+nsIBW6GT17cUdheUfYJ0qRD04x3A1M7EtFNrFPllo9UkqqlzkVLDu/X4rtk87bKBqog3/TfMpTPxamiWZUzuUSCsPUa9k1UM17Wv+FZkhkCfZiACNma767FRAQL5/JnoJ7vnLa/R2k9WglyxR6HsWaHfvjNv0FJ1OhgsAjBtJEfYyZYxsCTjxIzCoa1DZxzyKxFQ9Yl3jxjMA4/RLqRCF/iSyn/Zwv0uHOtNGiwzjQTLbQpS0RZWUFKDSZw5wN8ZUCDKaEjSgRXu88Gwf7MA+Xwyq07SnasdZFwoOx4VR81MZfu7skdGW18HTjsTQhqtsOvtZn1xyhYnu9B5L4y/+KP+hS8pMqTKUTn8BC5LjYWFTe7FA51s1C1IIyXBidB3TDPKJlG6hofhmF0PMEQyyOPDrFHom4hcmsPBKbswd+A1R0xiuArKlqxHuHSmRXEZZSc1tcqQ9/Oim8PhCn1k="
deploy:
  provider: rubygems
  gem: getto-repository
  on:
    tags: true
  api_key:
    secure: "wn/tjgSUCGLm2xXcb/NMJdyqtGzCIqQ76WFaMGoVwOYUghXIa0Q8ukFM8zK/BC7QOSzbKwfWwy9AznvXip7qC4vQnE1vlJZSZO6BQa7eEyNGcJ9nm6SJNygiHj3pgqx7nqgFbR9nqROdQkjKvz19yip5j/zAeLgKMSPLgB3nki1K2BUufXaXBK3OQfKEFUY2grTPwoGWpREgcnOFmmTtTpWB8+EoZUdEE05xLbSSsRMkolzDI3AykiVDv/geBMJ9Jrn9aLi9n/l4zCxNnfVLJKEm6HQBuVTNvT/DkLfim/HXJIQ69MbaCd2zKV8v0XUyiTzJTusmlIjPWURZHCLy81U04GX+Uyrmtj64P9buj4i35JsXLEGWvql3JyTkeGrKAZ2ufs5x0l0oF7l0NlpK4aySNumhrbIg0K9pHjgGWksmkIaejIiN30CluPag89KT5ASyxmoq+1sTN0NX+ozTp8+0ODso+hVY95KfCanF9++IHxlMyQPc7jhWq6+uiyg2aHsBaWfuPd3TtuIccHXOWCBbtJ0/AELjxX0WCAsnYAPTk3dczfeIIccr3Zr70vSLui7UCKKEmF6at+HioD+pGxz/g+cUWSQoIC25l3/F4ZY8sv8p2TqEWOj7DlIp3Ot4TgjRWjKWBzqTLVWhzKAJqhxYz8LaloVYpMyJ9G5hWqo="
